version: '3.8'

services:
    # Database
    db:
        image: postgres:13.4-buster
        container_name: postgres
        restart: always
        ports:
          - 5432:5432
        environment:
          POSTGRES_PASSWORD: "pass123"
          TZ: "Asia/Bangkok"
        volumes:
          - /home/pi/docker/postgres/pg_data:/var/lib/postgresql/data/

    # DBMS
    pgadmin:
        depends_on:
          - db
        image: biarms/pgadmin4:4.21
        container_name: pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: "postgres@domain.com"
          PGADMIN_DEFAULT_PASSWORD: "pass123"
        ports:
          - 5050:5050

volumes:
  pg_data:
