version: '3'

services:
    db:
        image: yobasystems/alpine-mariadb:10.4.15
        container_name: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
          MYSQL_ROOT_PASSWORD: "@Mephis2015"
          MYSQL_USER: "root"
          MYSQL_PASSWORD: "@Mephis2015"
          TZ: "Asia/Bangkok"
        ports:
          - 3306:3306
        volumes:
          - ./config/:/config
          - ./initdb/:/docker-entrypoint-initdb.d
          - ./data/:/var/lib/mysql

    phpmyadmin:
        depends_on:
          - db
        image: mt08/rpi-phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
          PMA_HOST: db
          PMA_ARBITARY: 1
        ports:
          - 8080:80
