version: '3.8'

services:
    redis:
        container_name: myredis
        image: redis:6.2.5-buster
        restart: unless-stopped
        ports:
          - "6379:6379"
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
          - /home/pi/docker/redis/data:/data # Used for persisting data
          - /home/pi/docker/redis/conf:/usr/local/etc/redis # Used for configuring redis

volumes:
    data:
    conf:
