version: '3'

services:
    # Mosquitto
    mqtt:
        container_name: mosquitto
        image: eclipse-mosquitto:2.0.11
        restart: always
        ports:
          - "1883:1883"
          - "9001:9001"
        volumes:
          - ./config:/mosquitto/config
          - ./data:/mosquitto/data
          - ./log:/mosquitto/log
volumes:
    config:
    data:
    log:
