app:
  host: "192.168.1.22"
  port: 8088

db:
  driver: "mysql"
  host: "192.168.176.2"
  # port: 3306
  username: "root"
  password: "@Mephis2015"
  database: "robotic"

mqtt:
  broker: "192.168.1.22"
  port: 1888
  username: "bot"
  password: "@Passw0rd"